name: "Sample CI pipeline for React framework"

on:
    push:
        branches:
            - master
            - main

jobs:
    built-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup of NodeJs"
              uses: actions/setup-node@v4 #this is github action
              with:
                node-version: '21'

            - name: "Check node version"
              run: node --version

            - name: "Cloning the repository"
              uses: actions/checkout@v4
              # also we can run linux command run: git clone <repo name>

            - name: "Listing the directories"
              run: ls

            - name: "Installing React Dependencies"
              run: npm install

            - name: "Listing the directories"
              run: ls
