name: "Sample CI pipeline for React framework"

on:
    push:
        branches:
            - master
            - main

jobs:
    built-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup of NodeJs"
              uses: actions/setup-node@v4 #this is github action
              with:
                node-version: '21'

            - name: "Check node version"
              run: node --version
